# Generated by Django 4.2.4 on 2023-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('office', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_autor', models.CharField(max_length=255)),
                ('nome_da_obra', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=14)),
                ('data_de_registro', models.DateField(default=0)),
            ],
        ),
    ]
